export { List as OrdersList } from "./pages/list/List"
export { Edit as OrdersEdit } from "./pages/edit/Edit"
export { Detail as OrdersDetail } from "./pages/detail/Detail"
export { EntityCard as OrderEntityCard } from "./components/EntityCard"
export { Field as OrderField } from "./components/Field"